name: Deploy EU27-Tracker

on:
  schedule:
    - cron: '0 18 * * *'  # 15 pm brasília
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  download_rank_files:
    runs-on: ubuntu-latest
    steps:
      - name: Download from Google Drive
        uses: satackey/action-google-drive@c6de6280a30b95db6c37c537328f902563974f1e
        with:
          # skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          download-from: /github/eu27-tracker/.tmp
          download-to: ./.tmp
          # For those who set up Google Drive API client ID and secret themselves
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.9
          cache: pip
      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v4.0.0
        with:
          path: requirements.txt
      - name: Build the website
        run: python main.py
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
  upload_rank_files:
    runs-on: ubuntu-latest
    steps:
        - name: Upload to Google Drive
          uses: satackey/action-google-drive@c6de6280a30b95db6c37c537328f902563974f1e
          with:
            # skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
            upload-from: ./.tmp
            upload-to: /github/eu27-tracker/.tmp
            # For those who set up Google Drive API client ID and secret themselves
            google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
            google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
