name: Deploy EU27-Tracker

on:
  schedule:
    - cron: '0 18 * * *'  # 15 pm brasília
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download rank files
        uses: synergy-au/download-workflow-artifacts-action@6f00b30f91f4ef692efd1019fdf3bddcde540238
        with:
          workflow-run-id: ${{ secrets.PREVIOUS_WORKFLOW }}
        continue-on-error: true
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.9
          cache: pip
      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v4.0.0
        with:
          path: requirements.txt
      - name: Build the website
        run: python main.py
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build
      - name: Upload rank files\
        uses: actions/upload-artifact@v3.1.1
        with:
          path: ./.tmp
          retention-days: 90
      - name: Save workflow ID
        run: |
          sudo apt-get install -y gh
          export GITHUB_TOKEN="${{ secrets.ACCESS_SECRETS_TOKEN }}"
          gh secret set PREVIOUS_WORKFLOW --body "${{ github.run_id }}"
      - name: Print the workflow ID
        run: echo ${{ github.run_id }}
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
